name: Personal website with Vite

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=carlos-ruiz
          -Dsonar.projectKey=carlos-ruiz_carlos-ruiz-website

    - name: Build
      run:
        npm install
        npm run build

  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setting heroku buildpack
      run:
        heroku buildpacks:set https://github.com/heroku/heroku-buildpack-static.git

    - name: Copy static file to source folder
      run:
        cp -a static.json dist/

    - name: Pushing files to heroku
      run:
        cd dist
        echo ${{ secrets.PRODUCTION_DOMAIN }} > CNAME
        git init
        git checkout -b main
        git add .
        git commit -m "My site ready for deployment."
        git remote add heroku ${{ secrets.HEROKU_GIT_REPO }}
        git push heroku main
